### ISSUE TITLE
DataclassBuilder cannot be inherited.

### ISSUE THREAD

**Issue by mrshannon** [mrshannon/dataclass-builder#1]
Child classes of `DataclassBuilder` throw an `AttributeError` on initialization.

Example
-----------

```python
from dataclasses import dataclass
from dataclass_builder import DataclassBuilder

@dataclass
class Something:
    pass

class ExtendedBuilder(DataclassBuilder):
    pass
```
Now if you construct an instance of the child class you get:

```python
>>> ExtendedBuilder(Something)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../dataclass-builder/dataclass_builder/__init__.py", line 190, in __init__
    self.__dataclass = dataclass
  File ".../dataclass-builder/dataclass_builder/__init__.py", line 218, in __setattr__
    elif item not in self.__settable_fields:
AttributeError: 'ExtendedBuilder' object has no attribute '_DataclassBuilder__settable_fields'
```

**Comment by mrshannon** [comment]
Closed with #2.
