### ISSUE TITLE
dataclass_builder factory fails building docstring with types form typing.

### ISSUE THREAD

**Issue by mrshannon** [mrshannon/dataclass-builder#9]
When using types from the typing module such as `Sequence` the `dataclass_builder` factory method fails building the class docstring for the generated class.

Example
-----------
The following example
```python
from typing import Sequence
from dataclasses import dataclass
from dataclass_builder import dataclass_builder

@dataclass
class ComplexTypes:
    sequence: Sequence[int]

ComplexTypes = dataclass_builder(ComplexTypes)
```
will throw an `AttributeError` because `typing.Sequence` does not have a `__name__` attribute.
```python
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    ComplexTypes = dataclass_builder(ComplexTypes)
  File ".../dataclass_builder/factory.py", line 372, in dataclass_builder
    for name, field in settable_fields.items()])
  File ".../dataclass_builder/factory.py", line 372, in <listcomp>
    for name, field in settable_fields.items()])
  File "/usr/lib/python3.7/typing.py", line 699, in __getattr__
    raise AttributeError(attr)
AttributeError: __name__

```

**Comment by mrshannon** [comment]
Closed by #10
